import type { StorybookConfig } from "@storybook/nextjs";
import path from "path";
import { fileURLToPath } from "url";

// ESM-safe __dirname replacement
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
import { VanillaExtractPlugin } from "@vanilla-extract/webpack-plugin";
import MiniCssExtractPlugin from "mini-css-extract-plugin";

const config: StorybookConfig = {
    stories: ["../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
    addons: [
        {
            name: "@storybook/addon-styling-webpack",
            options: {
                plugins: [
                    new VanillaExtractPlugin(),
                    new MiniCssExtractPlugin()
                ],
                rules: [
                    {
                        test: /\.css$/,
                        sideEffects: true,
                        use: [
                            "style-loader",
                            {
                                loader: "css-loader",
                                options: {}
                            }
                        ],
                        exclude: /\.vanilla\.css$/
                    },
                    {
                        // Targets only CSS files generated by vanilla-extract
                        test: /\.vanilla\.css$/i,
                        sideEffects: true,
                        use: [
                            MiniCssExtractPlugin.loader,
                            {
                                loader: "css-loader",
                                options: {
                                    // image imports should be handled via JS/TS import statements
                                    url: false
                                }
                            }
                        ]
                    }
                ]
            }
        }
    ],
    framework: {
        name: "@storybook/nextjs",
        options: {}
    },
    staticDirs: ["../public"],
    webpackFinal: async (config) => {
        if (config.resolve) {
            config.resolve.alias = {
                ...(config.resolve.alias as Record<string, string>),
                "@": path.resolve(__dirname, "../src")
            };
        }

        return config;
    }
};

export default config;
